// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzqFkOOZy6I_5rNyUHdlX99FJ4obL43gs',
    appId: '1:348081401529:web:cadd4c6d9d10c724587568',
    messagingSenderId: '348081401529',
    projectId: 'jumbo-8ceb4',
    authDomain: 'jumbo-8ceb4.firebaseapp.com',
    storageBucket: 'jumbo-8ceb4.appspot.com',
    measurementId: 'G-TEXXKB5KT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZUzEf5KP4jvAbP9myic_NyKeRDqlLtq8',
    appId: '1:348081401529:android:3081bacbd0d84d3a587568',
    messagingSenderId: '348081401529',
    projectId: 'jumbo-8ceb4',
    storageBucket: 'jumbo-8ceb4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWRm6SDSakxLDXHEzsERiDgaOCQVPS65Y',
    appId: '1:348081401529:ios:47413381899ff37f587568',
    messagingSenderId: '348081401529',
    projectId: 'jumbo-8ceb4',
    storageBucket: 'jumbo-8ceb4.appspot.com',
    iosBundleId: 'com.example.jumbo',
  );
}
